profile:
  default: slides
author:
    - name: Th√©ophile Gentilhomme, Nils Hanik
      institute: HES-SO Valais-Wallis
date: last-modified
date-format: long
  
bibliography: references.bib

format:
  revealjs:
    include-in-header: _quarto/includes/revealscript.html



